module.exports = [
  //['city','City',  'Город'],
  //['city2','City 2',  'Город2'],
  ['figure', 'Figure', 'Фигура'],
  ['figure2', 'Figure 2', 'Фигура2'],
  ['figure3', 'Figure 3', 'Фигура3'],
  //['flowers','Flowers',  'Цветы'],
  //['flowers2','Flowers 2',  'Цветы 2'],
  //['flowers3','Flowers 3',  'Цветы 3'],
  ['flowers4', 'Flowers 4', 'Цветы 4'],
  //['flowers5','Flowers 5',  'Цветы 5'],
  //['flowers6','Flowers 6',  'Цветы 6'],
  //['flowers7','Flowers 7',  'Цветы 7'],
  ['flower_basin', 'Flower basin', 'Ваза с цветами'],
  ['in_crinoline', 'In crinoline', 'В кринолине'],
  ['in_crinolines', 'In crinolines', 'В кринолинах'],
  ['in_crinolines2', 'In crinolines 2', 'В кринолинах 2'],
  ['in_dress', 'In dress', 'В платье'],
  ['in_dress2', 'In dress 2', 'В платье 2'],
  ['in_red', 'In red', 'В красном'],
  ['in_room', 'In room', 'В комнате'],
  ['is_seated', 'Is seated', 'Сидит'],
  ['lida', 'Lida', 'Лида'],
  ['lids', 'Lids', 'Лиды'],
  ['lilu', 'Lilu', 'Лилу'],
  ['lying', 'Lying', 'Лежащие'],
  ['lying1', 'Lying 1', 'Лежащая'],
  ['lying2', 'Lying 2', 'Лежащая 2'],
  ['lying3', 'Lying 3', 'Лежащие 2'],
  ['on_blue', 'On blue', 'На голубом'],
  ['pretty_flowers', 'Pretty flowers', 'Цветочки'],
  ['pretty_flowers2', 'Pretty flowers 2', 'Цветочки 2'],
  ['seated', 'Seated', 'Сидящая'],
  ['seated2', 'Seated 2', 'Сидящая 2'],
  ['seated3', 'Seated 3', 'Сидящая 3'],
  ['sitting', 'Sitting', 'Сидящие'],
  ['standing', 'Standing', 'Стоящие'],
  ['standing2', 'Standing 2', 'Стоящая'],
  ['still_life', 'Still-life', 'Натюрморт'],
  ['still_life2', 'Still-life 2', 'Натюрморт 2'],
  ['still_life3', 'Still-life 3', 'Натюрморт 3'],
  ['three', 'Three', 'Трое'],
  ['tulips', 'Tulips', 'Тюльпаны'],
  ['tulips2', 'Tulips 2', 'Тюльпаны 2'],
  ['tulips3', 'Tulips 3', 'Тюльпаны 3'],
  ['two_figures', 'Two figures', 'Композиция из двух фигур'],
  ['two_figures2', 'Two figures 2', 'Композиция из двух фигур 2'],
  ['with_basin', 'With basin', 'С чашей'],
  //['with_mirror','With mirror',  'С зеркалом'],
  ['with_mirror2', 'With mirror 2', 'С зеркалом 2'],
  ['with_mirror3', 'With mirror 3', 'С зеркалом 3'],
  ['with_mirror4', 'With mirror 4', 'С зеркалом 4'],
  ['lida_1', 'Lida 1', 'Лида 1'],
  ['lida_2', 'Lida 2', 'Лида 2'],
  ['lida_3', 'Lida 3', 'Лида 3'],
  ['lida_4', 'Lida 4', 'Лида 4'],
  ['lida_5', 'Lida 5', 'Лида 5'],
  ['lida_6', 'Lida 6', 'Лида 6'],
  ['lida_7', 'Lida 7', 'Лида 7'],
  ['lida_8', 'Lida 8', 'Лида 8'],
  ['lida_9', 'Lida 9', 'Лида 9'],
  ['lida_10', 'Lida 10', 'Лида 10'],
  ['lida_11', 'Lida 11', 'Лида 11'],
  ['lida_12', 'Lida 12', 'Лида 12'],
  ['lida_13', 'Lida 13', 'Лида 13'],
  ['lida_14', 'Lida 14', 'Лида 14'],
  ['lida_15', 'Lida 15', 'Лида 15'],
  ['lida_16', 'Lida 16', 'Лида 16'],
  ['lida_17', 'Lida 17', 'Лида 17'],
  ['lida_18', 'Lida 18', 'Лида 18'],
  ['lida_19', 'Lida 19', 'Лида 19'],
  ['olga', 'Olga', 'Ольга'],
];
