var items = {
    'city': {en: 'City', ru: 'Город'},
    'city2': {en: 'City 2', ru: 'Город2'},
    'figure': {en: 'Figure', ru: 'Фигура'},
    'figure2': {en: 'Figure 2', ru: 'Фигура2'},
    'figure3': {en: 'Figure 3', ru: 'Фигура3'},
    'flowers': {en: 'Flowers', ru: 'Цветы'},
    'flowers2': {en: 'Flowers 2', ru: 'Цветы 2'},
    'flowers3': {en: 'Flowers 3', ru: 'Цветы 3'},
    'flowers4': {en: 'Flowers 4', ru: 'Цветы 4'},
    'flowers5': {en: 'Flowers 5', ru: 'Цветы 5'},
    'flowers6': {en: 'Flowers 6', ru: 'Цветы 6'},
    'flowers7': {en: 'Flowers 7', ru: 'Цветы 7'},
    'flower_basin': {en: 'Flower basin', ru: 'Ваза с цветами'},
    'in_crinoline': {en: 'In crinoline', ru: 'В кринолине'},
    'in_crinolines': {en: 'In crinolines', ru: 'В кринолинах'},
    'in_crinolines2': {en: 'In crinolines 2', ru: 'В кринолинах 2'},
    'in_dress': {en: 'In dress', ru: 'В платье'},
    'in_dress2': {en: 'In dress 2', ru: 'В платье 2'},
    'in_red': {en: 'In red', ru: 'В красном'},
    'in_room': {en: 'In room', ru: 'В комнате'},
    'is_seated': {en: 'Is seated', ru: 'Сидит'},
    'lida': {en: 'Lida', ru: 'Лида'},
    'lids': {en: 'Lids', ru: 'Лиды'},
    'lilu': {en: 'Lilu', ru: 'Лилу'},
    'lying': {en: 'Lying', ru: 'Лежащие'},
    'lying1': {en: 'Lying 1', ru: 'Лежащая'},
    'lying2': {en: 'Lying 2', ru: 'Лежащая 2'},
    'lying3': {en: 'Lying 3', ru: 'Лежащие 2'},
    'on_blue': {en: 'On blue', ru: 'На голубом'},
    'pretty_flowers': {en: 'Pretty flowers', ru: 'Цветочки'},
    'pretty_flowers2': {en: 'Pretty flowers 2', ru: 'Цветочки 2'},
    'seated': {en: 'Seated', ru: 'Сидящая'},
    'seated2': {en: 'Seated 2', ru: 'Сидящая 2'},
    'seated3': {en: 'Seated 3', ru: 'Сидящая 3'},
    'sitting': {en: 'Sitting', ru: 'Сидящие'},
    'standing': {en: 'Standing', ru: 'Стоящие'},
    'standing2': {en: 'Standing 2', ru: 'Стоящая'},
    'still_life': {en: 'Still-life', ru: 'Натюрморт'},
    'still_life2': {en: 'Still-life 2', ru: 'Натюрморт 2'},
    'still_life3': {en: 'Still-life 3', ru: 'Натюрморт 3'},
    'three': {en: 'Three', ru: 'Трое'},
    'tulips': {en: 'Tulips', ru: 'Тюльпаны'},
    'tulips2': {en: 'Tulips 2', ru: 'Тюльпаны 2'},
    'tulips3': {en: 'Tulips 3', ru: 'Тюльпаны 3'},
    'two_figures': {en: 'Two figures', ru: 'Композиция из двух фигур'},
    'two_figures2': {en: 'Two figures 2', ru: 'Композиция из двух фигур 2'},
    'with_basin': {en: 'With basin', ru: 'С чашей'},
    'with_mirror': {en: 'With mirror', ru: 'С зеркалом'},
    'with_mirror2': {en: 'With mirror 2', ru: 'С зеркалом 2'},
    'with_mirror3': {en: 'With mirror 3', ru: 'С зеркалом 3'},
    'with_mirror4': {en: 'With mirror 4', ru: 'С зеркалом 4'}
};

module.exports = items;