module.exports = [
  ['lida_in_blue', '70x50', 2014, 'Lida in blue', 'Лида в синем'],
  ['on_pink', '72x77', 2014, 'On pink', 'На розовом'],
  [
    'stillife_on_black',
    '60x60',
    2014,
    'Stillife on black',
    'Натюрморт на черном',
  ],
  [
    'at_mirror_in_the_evening',
    '77x80',
    2013,
    'At mirror in the evening',
    'Вечером у зеркала',
  ],
  ['with_flowers', '82x53', 2013, 'With flowers', 'С цветами'],
  ['at_mirror', '60x50', 2005, 'At mirror', 'У зеркала'],
  ['at_table', '', 2005, 'At table', 'За столом'],
  ['basin', '80x90', 2008, 'Basin', 'Чаша'],
  ['big_stillife', '', 2005, 'Big still life', 'Большой натюрморт'],
  ['blue_stillife', '', 2006, 'Blue still life', 'Синий натюрморт'],
  ['blue_sugarbasin', '', 2006, 'Blue sugar basin', 'Синяя сахарница'],
  ['bouquet', '', 2010, 'Bouquet', 'Букет'],
  ['carnival', '', 2008, 'Carnival', 'Карнавал'],
  ['city', '', 2007, 'City', 'Город'],
  /*['dasha','', 2006, 'Dasha', 'Даша'],*/
  ['figures', '', 2007, 'Figures', 'Фигуры'],
  ['figure_on_black', '', 2007, 'Figure on black', 'Фигура на черном'],
  ['figure_on_blue', '', 2006, 'Figure on blue', 'Фигура на синем'],
  /*['figure_on_dark','', 2005, 'Figure on dark', 'Фигура на темном фоне'],*/
  /* ['figure_on_grass','', 2004, 'Figure on grass', 'Фигура на траве'],*/
  ['figure_on_white', '', 2007, 'Figure on white', 'Фигура на белом'],
  //['flowers_on_blue','', 2013, 'Flowers on blue', ru'Цветы на синем'],
  ['flowers_on_green', '', 2013, 'Flowers on green', 'Цветы на зеленом'],
  ['flowers_on_red', '', 2008, 'Flowers on red', 'Цветы на красном'],
  ['lida', '', 2007, 'Lida', 'Лида'],
  [
    'lida_in_carnival_dress',
    '',
    2007,
    'Lida in carnival dress',
    'Лида в карнавальном платье',
  ],
  [
    'lida_and_her_girlfriend',
    '',
    2007,
    'Lida and her girlfriend',
    'Лида с подружкой',
  ],
  ['lida_in_white', '', 2008, 'Lida in white', 'Лида в белом'],
  ['lida_with_flowers', '', 2008, 'Lida with flowers', 'Лида с цветами'],
  ['lids', '', 2008, 'Lids', 'Лиды'],
  ['naiza', '', 2010, 'Naiza', 'Наиза'],
  ['on_green', '', 2007, 'On green', 'На зеленом'],
  ['orange_stillife', '', 2007, 'Orange still life', 'Оранжевый натюрморт'],
  ['portrait', '', 2005, 'Portrait', 'Портрет'],
  ['spring', '', 2008, 'Spring', 'Весна'],
  ['spring2', '', 2008, 'Spring 2', 'Весна 2'],
  [
    'stillife_blue_basin',
    '',
    2005,
    'Still life with blue basin',
    'Натюрморт с синей вазой',
  ],
  [
    'stillife_with_tulips',
    '',
    2005,
    'Still life with tulips',
    'Натюрморт с тюльпанами',
  ],
  ['three_figures', '', 2006, 'Three figures', 'Три фигуры'],
  ['walk', '', 2007, 'Walk', 'Прогулка'],
  /*'white_stillife': {dims: '', year: 2006, en: 'White still life', ru: 'Белый натюрморт'},*/
  ['with_bird', '', 2010, 'With bird', 'С птицей'],
  ['with_bouquets', '', 2010, 'With bouquets', 'С букетами'],
  ['with_mirror', '', 2006, 'With mirror', 'С зеркалом'],
  [
    'flowers_on_green2',
    '72x77',
    2014,
    'Flowers on green 2',
    'Цветы на зеленом 2',
  ],
  ['do_you_know_lida', '72x77', 2014, 'Do you know Lida', 'Знаешь, Лида...'],
  ['bouquets', '82x72', 2014, 'Bouquets', 'Букеты'],
  [
    'flower_girl_on_green',
    '90x80',
    2014,
    'Flower-girl on green',
    'Цветочница на зеленом',
  ],
  ['lida_on_black', '84x94', 2014, 'Lida on black', 'Лида на черном'],
  ['lida_on_red', '50x70', 2014, 'Lida on red', 'Лида на красном'],
  ['lida_walking', '50x70', 2014, 'Lida walking', 'Лида на прогулке'],
  ['stillife', '70x70', 2014, 'Stillife', 'Натюрморт'],
  ['winter_stillife', '75x75', 2014, 'Winter stillife', 'Зимний натюрморт'],
];
